#!/usr/bin/python2
from sneakers import Exfil

mod = "googleSpread"

enc = ["b64"]

dataz = "very secret and private message"

print Exfil.list_encoders()

t = Exfil(mod, enc)
t.set_channel_params({'sending': {"keyfile": "key.json", "google_sheet":"helloworld"}})
t.set_channel_params({'receiving': {"keyfile": "key.json", "google_sheet":"helloworld"}})
t.set_encoder_params(enc[0], {})

print t.channel_config()
print t.encoder_config(enc[0])

t.send(dataz)

print t.receive()